'use strict';
const assert=require('assert');
const fs=require('fs');
const UI=require('../club_roster_identity_ui_v1.js');
const storage=()=>{const data=new Map();return {getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v))};};
const store=UI.createStore(storage());
assert.deepStrictEqual(store.bindings('analysis-A'),[]);
store.saveBindings([{trackId:1,playerId:'p1',validated:true}], 'analysis-A');
assert.strictEqual(store.bindings('analysis-A').length,1,'same analysis can retain confirmed bindings');
assert.deepStrictEqual(store.bindings('analysis-B'),[],'track #1 of a new video must not inherit identity from a previous video');
assert.deepStrictEqual(store.bindings(),[],'scoped records cannot become unscoped records');
store.saveBindings([{trackId:1,playerId:'p2',validated:true}], 'analysis-B');
assert.deepStrictEqual(store.bindings('analysis-A'),[],'superseded scope is not reused');
assert.strictEqual(store.bindings('analysis-B')[0].playerId,'p2');
store.saveBindings([{trackId:3,playerId:'legacy',validated:true}]);
assert.strictEqual(store.bindings().length,1,'legacy unscoped store API remains compatible');
assert.deepStrictEqual(store.bindings('analysis-C'),[],'legacy bindings cannot be imported into a new analysis');
const source=fs.readFileSync(require.resolve('../club_roster_identity_ui_v1.js'),'utf8');
assert(source.includes('activeAnalysisScope=scope'),'each tracking bridge instance must get its own analysis scope');
assert(!source.includes('store.bindings()'),'UI must not read unscoped persisted track IDs');
assert(!source.includes('store.saveBindings(lastSession.exportBindings());'),'manual confirmation must be scoped');
assert.strictEqual(source.split('store.saveBindings(lastSession.exportBindings(),activeAnalysisScope)').length-1,2,'confirm and unbind must save within active analysis');
console.log('analysis-scoped roster bindings non-regression: PASS');
