const assert=require('assert');
const app=require('../app_domain_models_v1.js');
let checks=0;
const ok=(cond,msg)=>{assert.ok(cond,msg);checks++;};
const eq=(a,b,msg)=>{assert.deepStrictEqual(a,b,msg);checks++;};
const club=app.createClub({id:'cay',name:'C.A. Yenne',shortName:'CAY'});
const roster=[];
for(let i=1;i<=13;i++)roster.push({id:String(i),firstName:`J${i}`,number:i,primaryPosition:i===1?'GK':'CM',status:i<=11?'ACTIVE':'SUBSTITUTE'});
const team=app.createTeam({id:'senior-a',clubId:'cay',name:'Seniors A',category:'Senior',roster,kits:[{id:'home',shirtColor:'yellow',shortsColor:'black',socksColor:'yellow'}],defaultLineup:roster.slice(0,11).map(x=>x.id),bench:roster.slice(11).map(x=>x.id)});
ok(team.roster.length===13,'roster may exceed 11');
ok(team.defaultLineup.length===11,'lineup has 11 players');
ok(team.roster[0].isGoalkeeper===true,'GK inferred from position');
eq(app.validateLineup(team).errors,[],'valid lineup has no errors');
const overflow={...team,defaultLineup:roster.slice(0,12).map(x=>x.id)};
ok(app.validateLineup(overflow).errors.includes('LINEUP_OVER_11'),'more than 11 blocked');
const overlap={...team,bench:['1','12']};
ok(app.validateLineup(overlap).errors.includes('PLAYER_IN_LINEUP_AND_BENCH'),'lineup/bench overlap blocked');
const inactiveLineup={...team,roster:team.roster.map(p=>p.id==='2'?{...p,status:'INACTIVE'}:p)};
ok(app.validateLineup(inactiveLineup).errors.includes('INACTIVE_PLAYER_IN_LINEUP'),'inactive player cannot be launched on field');
const inactiveBench={...team,roster:team.roster.map(p=>p.id==='12'?{...p,status:'INACTIVE'}:p)};
ok(app.validateLineup(inactiveBench).errors.includes('INACTIVE_PLAYER_ON_BENCH'),'inactive player cannot be launched on bench');
const emptyLineup={...team,defaultLineup:[]};
const emptyLineupValidation=app.validateLineup(emptyLineup);
ok(emptyLineupValidation.errors.includes('LINEUP_EMPTY'),'analysis requires at least one selected on-field player');
ok(emptyLineupValidation.minActive===1,'minimum active selection is explicit');
const profile=app.createAnalysisProfile({id:'standard',teamId:team.id});
ok(profile.settings.trackingSensitivity===0.7,'tracking default explicit');
ok(profile.settings.reidThreshold===0.78,'reid default explicit');
ok(profile.settings.manualReview===true,'manual review defaults on');
const ready=app.setupReadiness({club,team,analysisProfile:profile});
ok(ready.ready===true,'configured team is ready');
ok(ready.targetSetupMinutes===20,'UX target retained');
ok(ready.missing.length===0,'ready setup has no missing fields');
ok(ready.selectedKitId==='home','single usable kit is selected automatically');
ok(ready.kitSelection.mode==='AUTO_SINGLE','single-kit path adds no setup step');
const multiKitTeam=app.createTeam({id:'multi-kit',clubId:'cay',name:'Seniors B',category:'Senior',roster:roster.slice(0,5),kits:[{id:'home',shirtColor:'red'},{id:'away',shirtColor:'white'}],defaultLineup:roster.slice(0,5).map(x=>x.id)});
const multiKitProfile=app.createAnalysisProfile({teamId:'multi-kit'});
const ambiguousKit=app.setupReadiness({club,team:multiKitTeam,analysisProfile:multiKitProfile});
ok(ambiguousKit.ready===false,'multiple usable kits require an explicit active kit');
ok(ambiguousKit.missing.includes('KIT'),'ambiguous active kit blocks launch');
ok(ambiguousKit.kitSelection.mode==='AMBIGUOUS','ambiguous kit state is explicit');
const selectedAway=app.setupReadiness({club,team:multiKitTeam,analysisProfile:multiKitProfile,selectedKitId:'away'});
ok(selectedAway.ready===true,'explicit usable active kit enables launch');
ok(selectedAway.selectedKitId==='away','explicit active kit is preserved');
const unknownKit=app.setupReadiness({club,team:multiKitTeam,analysisProfile:multiKitProfile,selectedKitId:'third'});
ok(unknownKit.ready===false,'unknown active kit cannot launch analysis');
ok(unknownKit.kitSelection.mode==='INVALID_EXPLICIT','invalid explicit kit is auditable');
const wrongTeamProfile=app.setupReadiness({club,team,analysisProfile:app.createAnalysisProfile({id:'other-profile',teamId:'another-team'})});
ok(wrongTeamProfile.ready===false,'profile from another team cannot launch analysis');
ok(wrongTeamProfile.missing.includes('ANALYSIS_PROFILE_TEAM'),'profile/team mismatch is explicit');
const unusableKitTeam=app.createTeam({id:'no-shirt-colour',clubId:'cay',name:'Sans couleur maillot',category:'Senior',roster:roster.slice(0,5),kits:[{id:'home',shortsColor:'black'}],defaultLineup:roster.slice(0,5).map(x=>x.id)});
const unusableKitReady=app.setupReadiness({club,team:unusableKitTeam,analysisProfile:app.createAnalysisProfile({teamId:'no-shirt-colour'})});
ok(unusableKitReady.ready===false,'kit without shirt colour cannot claim launch readiness');
ok(unusableKitReady.missing.includes('KIT'),'shirt colour evidence required for usable kit');
const rosterButNoLineup=app.createTeam({id:'training',clubId:'cay',name:'Séance',category:'Senior',roster:roster.slice(0,5),kits:[{id:'home',shirtColor:'red',shortsColor:'black',socksColor:'red'}]});
const lineupMissing=app.setupReadiness({club,team:rosterButNoLineup,analysisProfile:app.createAnalysisProfile({teamId:'training'})});
ok(lineupMissing.ready===false,'roster and kit alone cannot claim launch readiness');
ok(lineupMissing.missing.includes('LINEUP_VALID'),'setup exposes missing on-field selection');
const incomplete=app.setupReadiness({club:app.createClub({}),team:app.createTeam({})});
ok(incomplete.ready===false,'empty setup not ready');
ok(incomplete.missing.includes('CLUB_NAME'),'club name required');
ok(incomplete.missing.includes('TEAM_NAME'),'team name required');
ok(incomplete.missing.includes('ROSTER'),'roster required');
ok(incomplete.missing.includes('KIT'),'kit required');
ok(incomplete.missing.includes('LINEUP_VALID'),'empty setup also reports missing lineup');
const user=app.createUser({id:'u1',displayName:'Coach'});
ok(user.auth.status==='BACKEND_REQUIRED','auth remains backend-dependent');
let secretBlocked=false;
try{app.createUser({displayName:'Coach',password:'plaintext'});}catch(e){secretBlocked=/SECRET_FIELD_FORBIDDEN/.test(e.message);}
ok(secretBlocked,'plaintext password field rejected');
let nestedSecretBlocked=false;
try{app.createUser({displayName:'Coach',auth:{credentials:{refresh_token:'plaintext'}}});}catch(e){nestedSecretBlocked=e.message==='SECRET_FIELD_FORBIDDEN:auth.credentials.refresh_token';}
ok(nestedSecretBlocked,'nested normalized secret field rejected with auditable path');
let arraySecretBlocked=false;
try{app.createUser({displayName:'Coach',providers:[{name:'future',accessToken:'plaintext'}]});}catch(e){arraySecretBlocked=e.message==='SECRET_FIELD_FORBIDDEN:providers[0].accessToken';}
ok(arraySecretBlocked,'secret hidden inside arrays rejected');
const cyclic={displayName:'Coach'}; cyclic.self=cyclic;
const cyclicUser=app.createUser(cyclic);
ok(cyclicUser.auth.status==='BACKEND_REQUIRED','cyclic metadata does not break secret scan');
let badPosition=false;
try{app.createPlayer({id:'bad',primaryPosition:'TREE'});}catch(e){badPosition=e.message==='INVALID_PRIMARY_POSITION';}
ok(badPosition,'invalid position rejected');
let duplicate=false;
try{app.createTeam({roster:[{id:'1'},{id:'1'}]});}catch(e){duplicate=e.message==='DUPLICATE_PLAYER_ID';}
ok(duplicate,'duplicate roster ids rejected');
let matchState=app.createMatchState(team);
matchState=app.applySubstitution(team,matchState,{outPlayerId:'11',inPlayerId:'12',atMs:30000,reason:'TACTICAL'});
matchState=app.applySubstitution(team,matchState,{outPlayerId:'12',inPlayerId:'13',atMs:60000,reason:'TACTICAL'});
const participation=app.deriveParticipationWindows(team,matchState,90000);
eq(participation.byPlayerId['11'],[{startMs:0,endMs:30000}],'starter participation closes exactly at substitution');
eq(participation.byPlayerId['12'],[{startMs:30000,endMs:60000}],'substitute participation starts and closes on event times');
eq(participation.byPlayerId['13'],[{startMs:60000,endMs:90000}],'second substitute remains active through analysis end');
ok(app.isPlayerActiveAt(participation,'11',29999)===true,'starter active before exit');
ok(app.isPlayerActiveAt(participation,'11',30001)===false,'starter inactive after exit');
ok(app.isPlayerActiveAt(participation,'12',45000)===true,'substitute active only inside participation window');
ok(app.isPlayerActiveAt(participation,'13',59999)===false,'future substitute excluded before entry');
ok(participation.finalActivePlayerIds.length===11,'participation replay preserves maximum active team state');
const starterTrack={globalId:11,fullPath:[{time:29.5,segment:1,x:.1,y:.1},{time:30,segment:1,x:.2,y:.2},{time:30.5,segment:1,x:.3,y:.3}]};
const starterSplit=app.splitTrackEvidenceByParticipation(participation,'11',starterTrack);
ok(starterSplit.acceptedObservations===2,'starter track keeps only points through confirmed exit');
ok(starterSplit.rejectedObservations===1,'starter track rejects point after confirmed exit');
eq(starterSplit.windows[0].track.fullPath.map(p=>p.time),[29.5,30],'starter metric evidence is bounded by participation window');
const rollingParticipation={...participation,byPlayerId:{...participation.byPlayerId,'12':[{startMs:10000,endMs:20000},{startMs:40000,endMs:50000}]}};
const rollingTrack={globalId:12,fullPath:[{time:15,segment:1,x:.1,y:.1},{time:25,segment:1,x:.2,y:.2},{time:45,segment:1,x:.3,y:.3}]};
const rollingSplit=app.splitTrackEvidenceByParticipation(rollingParticipation,'12',rollingTrack);
ok(rollingSplit.windows.length===2,'separate participation windows remain separate metric inputs');
eq(rollingSplit.windows.map(w=>w.track.fullPath.map(p=>p.time)),[[15],[45]],'no cross-window track join is created');
ok(rollingSplit.rejectedObservations===1,'between-window observation is explicitly rejected');
ok(rollingSplit.policy==='SEPARATE_PARTICIPATION_WINDOWS_NO_CROSS_WINDOW_METRIC_JOIN','continuity policy is explicit');
let invalidScale=false;
try{app.splitTrackEvidenceByParticipation(participation,'11',starterTrack,{timeScaleMs:0});}catch(e){invalidScale=e.message==='PARTICIPATION_TIME_SCALE_INVALID';}
ok(invalidScale,'invalid time unit conversion fails closed');
let inconsistentHistory=false;
try{app.deriveParticipationWindows(team,{...matchState,substitutions:[...matchState.substitutions].reverse()},90000);}catch(e){inconsistentHistory=/SUBSTITUTION_TIME_REGRESSION/.test(e.message);}
ok(inconsistentHistory,'out-of-order substitution history rejected');
console.log(`app_domain_models_nonregression: ${checks} checks PASS`);