'use strict';
const assert=require('assert');
const K=require('../metric_player_kinematics_v1.js');
const traj=(runs,extra)=>Object.assign({status:'DISPONIBLE',runs,metricCoverage:1,avgCalibrationConfidence:1},extra||{});
const p=(time,x,y,segmentId)=>({time,x,y,segmentId:segmentId||'A'});
let r=K.build(null);
assert.strictEqual(r.status,'INDISPONIBLE');assert.strictEqual(r.distanceM,null);
r=K.build(traj([[p(0,0,0),p(1,5,0)]],{metricCoverage:.2}));assert.strictEqual(r.status,'INDISPONIBLE');assert.match(r.reason,/couverture/);
r=K.build(traj([[p(0,0,0),p(1,5,0)]],{avgCalibrationConfidence:.2}));assert.strictEqual(r.status,'INDISPONIBLE');assert.match(r.reason,/calibration/);
r=K.build(traj([[p(0,0,0),p(1,5,0),p(2,10,0)]]));assert.strictEqual(r.status,'DISPONIBLE');assert.strictEqual(r.distanceM,10);assert.strictEqual(r.validSeconds,2);assert.strictEqual(r.avgSpeedKmh,18);assert.strictEqual(r.maxSpeedKmh,18);assert.strictEqual(r.sprintCount,0);assert.strictEqual(r.interpolation,'NONE');
r=K.build(traj([[p(0,0,0),p(2,10,0)]]),{maxGapSec:1});assert.strictEqual(r.status,'INDISPONIBLE');assert.strictEqual(r.distanceM,null);
r=K.build(traj([[p(0,0,0),p(1,20,0)]]));assert.strictEqual(r.status,'INDISPONIBLE');assert.strictEqual(r.distanceM,null);
r=K.build(traj([[p(0,0,0),p(.5,4,0),p(1,8,0),p(1.5,12,0)]]),{sprintThresholdKmh:25,minSprintDurationSec:1});assert.strictEqual(r.status,'DISPONIBLE');assert.strictEqual(r.sprintCount,1);assert.strictEqual(r.sprintDistanceM,12);assert.strictEqual(r.sprintSeconds,1.5);
r=K.build(traj([[p(0,0,0),p(.5,4,0)],[p(1,8,0),p(1.5,12,0)]]),{sprintThresholdKmh:25,minSprintDurationSec:1});assert.strictEqual(r.status,'DISPONIBLE');assert.strictEqual(r.sprintCount,0,'separate runs must never be stitched into a sprint');
console.log('metric player kinematics non-regression: PASS');
