const assert=require('assert');
const fs=require('fs');

const integrator=fs.readFileSync('tools/integrate_tracking_v2.py','utf8');
const html=fs.readFileSync('CAY_ANALYZER_STABLE.html','utf8');
const tag='<script src="./motchallenge_tracking_artifact_adapter_v1.js"></script>';
const trackingCore='<script src="./tracking_core_v1.js"></script>';
const stableRuntime='<script src="./stable_runtime_tracking_v2.js"></script>';

assert.ok(integrator.includes(tag),'MOT/TrackLab artifact adapter must be in canonical STABLE manifest');
const manifestTag=integrator.indexOf(tag);
const manifestTracking=integrator.indexOf(trackingCore);
const manifestRuntime=integrator.indexOf(stableRuntime);
assert.ok(manifestTag>=0&&manifestTag<manifestTracking&&manifestTracking<manifestRuntime,'artifact adapter must load before tracking core and STABLE runtime');

// The checked-in HTML may be regenerated by the integrator in CI. If already integrated,
// keep the same uniqueness/order contract; otherwise the integration job will insert it.
const occurrences=html.split(tag).length-1;
assert.ok(occurrences===0||occurrences===1,'MOT artifact runtime tag must never be duplicated');
if(occurrences===1){
  assert.ok(html.indexOf(tag)<html.indexOf(trackingCore),'integrated MOT adapter must precede tracking core');
}

const adapter=require('../motchallenge_tracking_artifact_adapter_v1.js');
assert.strictEqual(typeof adapter.createArtifact,'function','runtime manifest must point at the artifact constructor');
assert.strictEqual(typeof adapter.detectionsAt,'function','runtime manifest must point at the guarded temporal query API');
const artifact=adapter.createArtifact([
  {frame:1,track_id:7,bbox_ltwh:[100,50,20,40],score:.9,category_id:1}
],{
  width:640,height:360,fps:25,classMap:{'1':'team'},requireWeightProvenance:false,
  provenance:{source:'runtime-manifest-test',license:'MIT',revision:'test-v1'}
});
const sample=adapter.detectionsAt(artifact,0,{maxAgeSec:.01});
assert.strictEqual(sample.status,'AVAILABLE','loaded runtime adapter must return a fresh guarded sample');
assert.strictEqual(sample.detections.length,1);
assert.strictEqual(sample.detections[0].sourceTrackId,7);
console.log('motchallenge_tracking_artifact_runtime_manifest_nonregression: PASS');
