const assert=require('assert');
const fs=require('fs');

const integrator=fs.readFileSync('tools/integrate_tracking_v2.py','utf8');
const html=fs.readFileSync('CAY_ANALYZER_STABLE.html','utf8');
const tag='<script src="./motchallenge_tracking_artifact_adapter_v1.js"></script>';
const trackingCore='<script src="./tracking_core_v1.js"></script>';
const stableRuntime='<script src="./stable_runtime_tracking_v2.js"></script>';

assert.ok(integrator.includes(tag),'MOT/TrackLab artifact adapter must be in canonical STABLE manifest');
const manifestTag=integrator.indexOf(tag);
const manifestTracking=integrator.indexOf(trackingCore);
const manifestRuntime=integrator.indexOf(stableRuntime);
assert.ok(manifestTag>=0&&manifestTag<manifestTracking&&manifestTracking<manifestRuntime,'artifact adapter must load before tracking core and STABLE runtime');

// The checked-in HTML may be regenerated by the integrator in CI. If already integrated,
// keep the same uniqueness/order contract; otherwise the integration job will insert it.
const occurrences=html.split(tag).length-1;
assert.ok(occurrences===0||occurrences===1,'MOT artifact runtime tag must never be duplicated');
if(occurrences===1){
  assert.ok(html.indexOf(tag)<html.indexOf(trackingCore),'integrated MOT adapter must precede tracking core');
}

const adapter=require('../motchallenge_tracking_artifact_adapter_v1.js');
assert.strictEqual(typeof adapter.adapt,'function','runtime manifest must point at a usable adapter module');
console.log('motchallenge_tracking_artifact_runtime_manifest_nonregression: PASS');
