'use strict';
const assert=require('assert');
const Presence=require('../observed_presence_v1.js');
const Report=require('../observed_presence_report_v1.js');
const s=Presence.createState();
const candidates=Array.from({length:12},(_,i)=>({trackId:i+1,score:.99-i*.01,cat:'CAY'}));
const overflow=Presence.observeFrame(s,candidates,0,{segment:1});
assert.strictEqual(overflow.observedCount,0);
assert.strictEqual(overflow.quality,'INDISPONIBLE');
assert.strictEqual(overflow.evidenceValid,false);
assert.strictEqual(overflow.evidenceReason,'MORE_THAN_11_CAY_IDS');
assert.strictEqual(overflow.candidateCount,12);
assert.strictEqual(overflow.rejectedOverflowCount,1);
assert.strictEqual(Presence.summarize(s).rosterSize,0);
const clean=Presence.observeFrame(s,candidates.slice(0,11),1,{segment:1});
assert.strictEqual(clean.observedCount,11);
assert.strictEqual(clean.quality,'FIABLE');
assert.strictEqual(Presence.summarize(s).rosterSize,11);
const report=Report.buildPresenceReport(s,[],{});
assert.strictEqual(report.observedInstants,2);
assert.strictEqual(report.invalidObservedInstants,1);
assert.strictEqual(report.validObservedInstants,1);
assert.strictEqual(report.frames[0].frameEvidenceValid,false);
assert.strictEqual(report.frames[0].frameEvidenceReason,'MORE_THAN_11_CAY_IDS');
assert.strictEqual(report.frames[0].presentCount,0);
assert.strictEqual(report.frames[0].rejectedOverflowIds,1);
assert.strictEqual(report.frames[1].frameEvidenceValid,true);
assert.strictEqual(report.observedPlayerSlots,11);
assert.strictEqual(report.possiblePlayerSlots,11);
assert.strictEqual(report.invalidFrameEvidence.overflowIds,1);
assert.strictEqual(report.rejectedOverflow,1);
console.log('observed presence overflow fail-closed non-regression: PASS (22 assertions)');
