const assert=require('assert');
const presence=require('../observed_presence_v1.js');
const bridge=require('../observed_presence_report_v1.js');
let pass=0;
const ok=(cond,msg)=>{assert.ok(cond,msg);pass++;};
const state=presence.createState();
const frame=(ids,time,segment)=>presence.observeFrame(state,ids.map((id,i)=>({trackId:id,score:.9-(i*.01),cat:id===1?'GK':'CAY'})),time,{segment});
frame([1,2,3,4,5,6,7,8,9,10,11],0,1);
frame([1,2,3,4,5,6,7,8],1,1);
frame([1,2,3,4,5,6,7,8,9,10,12],2,2);
const cards=Array.from({length:12},(_,i)=>({id:i+1,identityQuality:(i===7||i===11)?'PARTIEL':'FIABLE'}));
const projectors={2:{validated:true,source:'manual_4_points',confidence:.96,project:p=>({x:p.x*100,y:p.y*60})}};
const report=bridge.buildPresenceReport(state,cards,projectors);
ok(report.rosterSize===12,'roster global supérieur à 11 conservé');
ok(report.maxObservedSimultaneously===11,'maximum simultané limité à 11');
ok(report.observedInstants===3,'trois instants observés');
ok(report.observedPlayerSlots===30,'slots observés réels sans complétion silencieuse');
ok(report.possiblePlayerSlots===33,'dénominateur 11 par instant explicite');
ok(report.presenceCoverage===0.9091,'couverture présence instantanée correcte');
ok(report.frames[1].presentCount===8,'frame partielle garde seulement huit joueurs observés');
ok(report.frames[1].presenceQuality==='PARTIEL','frame à huit joueurs classée partielle');
ok(report.frames[2].presentIds.includes(12),'nouveau joueur du roster visible au plan 2');
ok(report.frames[2].metricProjectionValidated===true,'projection plan 2 reconnue');
ok(report.frames[0].metricProjectionValidated===false,'plan 1 non calibré reste non métrique');
ok(report.metricProjectionCoverage===0.3667,'couverture projection pondérée par joueurs observés');
ok(report.frames.every(f=>new Set(f.presentIds).size===f.presentIds.length),'aucun doublon ID dans le rapport');
ok(report.policy.noSilentCompletion===true,'interdiction de compléter silencieusement les joueurs manquants');
ok(report.policy.substitutions==='NEVER_INFERRED_FROM_PRESENCE','aucun remplacement inféré depuis la présence');
const applied=bridge.applyToReport({players:cards,team:{foo:1},teamCoverage:{}},state,projectors);
ok(applied.team.observedPlayerSlots===30,'rapport équipe raccordé au registre observé');
ok(applied.team.instantaneousPresenceCoverage===0.9091,'couverture présence exposée au rapport équipe');
ok(applied.teamTimeline[1].presentCount===8,'timeline équipe remplacée par la timeline observée canonique');
ok(applied.teamCoverage.identity===report.identityCoverage,'couverture identité issue des seuls joueurs présents');
ok(applied.presenceEvidence.source===undefined && applied.presenceEvidence.policy.source==='OBSERVED_PRESENCE_LEDGER','provenance observée conservée');
const unavailable=bridge.applyToReport({players:[]},null,{});
ok(unavailable.presenceEvidence.quality==='INDISPONIBLE','absence de registre jamais masquée par une estimation');
console.log(`PASS ${pass}/21 observed presence report`);
