'use strict';
const assert=require('assert');
const R=require('../player_card_renderer_v1.js');
const unavailable={status:'INDISPONIBLE',value:null};
const card={id:7,category:'player',identity:{status:'FIABLE'},presence:{observedDuration:61.2,observations:44,trackingCoverage:83},observedVisuals:{status:'DISPONIBLE',heatmap:{cols:2,cells:[[1,2],[0,3]]}},pitchVisuals:{status:'INDISPONIBLE'},metrics:{distanceM:unavailable,avgSpeedKmh:unavailable,maxSpeedKmh:unavailable,sprintCount:unavailable}};
const html=R.cardHtml(card);
assert(html.includes('J • track 7'),'unbound technical track identity must remain visible without impersonating a shirt number');
assert(html.includes('Roster non lié — aucune identité déduite automatiquement'),'unbound track must explicitly state that no roster identity was inferred');
assert(html.includes('CAMÉRA • 83 %'),'observed tracking coverage must be explicit');
assert(html.includes('TERRAIN INDISPONIBLE'),'metric-space availability must be explicit');
assert(html.includes('Distance</span><br><b>INDISPONIBLE'),'distance must never be fabricated without metric evidence');
assert(html.includes('PRÉSENCE CAMÉRA — PAS UNE CARTE TACTIQUE'),'image-space heatmap must not be presented as tactical pitch occupation');
assert(!html.includes('OCCUPATION TERRAIN VALIDÉE'),'pitch section must stay hidden without defended pitch visuals');
assert(!html.includes('TRAJECTOIRE TERRAIN VALIDÉE'),'pitch trajectory must stay hidden without defended pitch visuals');
const linked={...card,roster:{status:'LIÉ',displayName:'Louis Test',number:8,photoUrl:'photos/p1.jpg',primaryPosition:'CM',secondaryPosition:'AM'}};
const linkedHtml=R.cardHtml(linked);
assert(linkedHtml.includes('Louis Test #8'),'validated roster identity must render name and shirt number');
assert(linkedHtml.includes('CM / AM • track 7'),'validated roster identity must render positions while preserving technical track provenance');
assert(linkedHtml.includes('photos/p1.jpg'),'validated roster photo should be renderable');
const trajectory={status:'DISPONIBLE',runs:[[{time:0,segment:1,x:5,y:10},{time:.5,segment:1,x:30,y:20}],[{time:2,segment:1,x:60,y:35},{time:2.5,segment:1,x:90,y:50}]]};
const metric={...card,pitchVisuals:{status:'DISPONIBLE',metricCoverage:71,pitchLengthM:105,pitchWidthM:68,heatmap:{cols:2,rows:1,normalizedCells:[[.25,.75]]},trajectory},metrics:{distanceM:{status:'PARTIEL',value:1234.4},avgSpeedKmh:{status:'PARTIEL',value:7.52},maxSpeedKmh:{status:'PARTIEL',value:24.18},sprintCount:{status:'PARTIEL',value:0}}};
const html2=R.cardHtml(metric);
assert(html2.includes('1234 m'),'defended distance must render');
assert(html2.includes('0</b>'),'a defended zero sprint count must not become unavailable');
assert(html2.includes('OCCUPATION TERRAIN VALIDÉE'),'validated pitch heatmap must render separately');
assert(!html2.includes('Heatmap indisponible'),'runtime normalizedCells heatmap payload must render without requiring legacy cells');
assert(html2.includes('TRAJECTOIRE TERRAIN VALIDÉE'),'validated metric trajectory must be visible in the player card');
assert(html2.includes('aria-label="trajectoire terrain joueur"'),'trajectory must render as an accessible pitch SVG');
assert((html2.match(/<polyline /g)||[]).length===2,'trajectory gaps/runs must remain separated instead of being silently interpolated');
assert(html2.includes('viewBox="0 0 105 68"'),'trajectory must use explicit metric pitch dimensions');
assert(R.trajectoryHtml(trajectory,null,68).includes('Trajectoire terrain indisponible'),'missing pitch dimensions must fail closed');
assert(R.metricText(null,'m')==='INDISPONIBLE');
console.log('player card renderer non-regression: PASS');
