'use strict';
const assert=require('assert');
const Session=require('../player_identity_binding_session_v1.js');
const team={id:'cay',roster:[{id:'p1',displayName:'Gardien',number:1,primaryPosition:'GK'},{id:'p2',displayName:'Attaquant',number:9,primaryPosition:'ST'}]};
const binding=(trackId,playerId)=>({trackId,playerId,validated:true,confidence:1,source:'coach_click'});
const stale=Session.createSession({team,tracks:[{id:7}],bindings:[binding(99,'p1')]});
assert.strictEqual(stale.summary().linked,0,'stale track must not count');
assert.strictEqual(stale.summary().unlinked,1,'current track remains unidentified');
assert.strictEqual(stale.summary().complete,false,'stale track must not complete session');
assert.deepStrictEqual(stale.exportBindings(),[],'stale binding must not be re-exported');
assert.deepStrictEqual(stale.candidates(7).map(x=>x.id),['p1','p2'],'stale link must not reserve a roster player');
const mixed=Session.createSession({team,tracks:[{id:7}],bindings:[binding('7','p1'),binding(99,'p2')]});
assert.strictEqual(mixed.summary().linked,1,'valid current binding survives');
assert.strictEqual(mixed.summary().unlinked,0);
assert.strictEqual(mixed.exportBindings().length,1);
assert.strictEqual(mixed.exportBindings()[0].trackId,7,'canonical numeric track ID retained');
assert.deepStrictEqual(mixed.candidates(7).map(x=>x.id),['p1','p2'],'stale link must not hide other players');
const empty=Session.createSession({team,tracks:[],bindings:[binding(99,'p1')]});
assert.strictEqual(empty.summary().linked,0);
assert.strictEqual(empty.summary().unlinked,0);
assert.strictEqual(empty.summary().complete,false);
console.log('player identity stale track non-regression: PASS');
