'use strict';
const assert=require('assert');
const R=require('../player_card_renderer_v1.js');
const unavailable={status:'INDISPONIBLE',value:null};
const card={id:7,category:'player',identity:{status:'FIABLE'},presence:{observedDuration:61.2,observations:44,trackingCoverage:83},observedVisuals:{status:'DISPONIBLE',heatmap:{cols:2,cells:[[1,2],[0,3]]}},pitchVisuals:{status:'INDISPONIBLE'},metrics:{distanceM:unavailable,avgSpeedKmh:unavailable,maxSpeedKmh:unavailable,sprintCount:unavailable}};
const html=R.cardHtml(card);
assert(html.includes('J • track 7'),'unbound technical track identity must remain visible without impersonating a shirt number');
assert(html.includes('Roster non lié — aucune identité déduite automatiquement'),'unbound track must explicitly state that no roster identity was inferred');
assert(html.includes('CAMÉRA • 83 %'),'observed tracking coverage must be explicit');
assert(html.includes('TERRAIN INDISPONIBLE'),'metric-space availability must be explicit');
assert(html.includes('Distance</span><br><b>INDISPONIBLE'),'distance must never be fabricated without metric evidence');
assert(html.includes('PRÉSENCE CAMÉRA — PAS UNE CARTE TACTIQUE'),'image-space heatmap must not be presented as tactical pitch occupation');
assert(!html.includes('OCCUPATION TERRAIN VALIDÉE'),'pitch section must stay hidden without defended pitch visuals');
const linked={...card,roster:{status:'LIÉ',displayName:'Louis Test',number:8,photoUrl:'photos/p1.jpg',primaryPosition:'CM',secondaryPosition:'AM'}};
const linkedHtml=R.cardHtml(linked);
assert(linkedHtml.includes('Louis Test #8'),'validated roster identity must render name and shirt number');
assert(linkedHtml.includes('CM / AM • track 7'),'validated roster identity must render positions while preserving technical track provenance');
assert(linkedHtml.includes('photos/p1.jpg'),'validated roster photo should be renderable');
const metric={...card,pitchVisuals:{status:'DISPONIBLE',metricCoverage:71,heatmap:{cols:1,cells:[[4]]}},metrics:{distanceM:{status:'PARTIEL',value:1234.4},avgSpeedKmh:{status:'PARTIEL',value:7.52},maxSpeedKmh:{status:'PARTIEL',value:24.18},sprintCount:{status:'PARTIEL',value:0}}};
const html2=R.cardHtml(metric);
assert(html2.includes('1234 m'),'defended distance must render');
assert(html2.includes('0</b>'),'a defended zero sprint count must not become unavailable');
assert(html2.includes('OCCUPATION TERRAIN VALIDÉE'),'validated pitch heatmap must render separately');
assert(R.metricText(null,'m')==='INDISPONIBLE');
console.log('player card renderer non-regression: PASS');
