const fs=require('fs');
const src=fs.readFileSync('stable_runtime_tracking_v2.js','utf8');
let pass=0,fail=0;
function check(name,cond){if(cond){console.log('PASS',name);pass++;}else{console.error('FAIL',name);fail++;}}
check('uses long-term bridge',src.includes('CAYStableTrackingBridge.create'));
check('hard cap 11 players',src.includes('maxPlayers:11'));
check('feeds all classified CAY candidates to strict frame guard',src.includes("const frameCls=classifyFrameDetections(c,inField),dets=[]"));
check('does not pre-truncate CAY candidates with football squad limiter',!src.includes('const frameCls=classifyFootballFrame(c,inField),dets=[]'));
check('fails closed if unbounded classifier is unavailable',src.includes("throw new Error('classifieur CAY non tronqué indisponible')"));
check('feeds visual segment-break evidence to bridge',src.includes('sceneCutScore')&&src.includes('visualDiscontinuity'));
check('does not split camera segment from sparse detections alone',!src.includes('sparseFrames')&&!src.includes("segmentReason:strongCut?'visual_cut':'sparse_team'"));
check('appearance vector for re-identification',src.includes('appearanceVector(cls.feature)'));
check('no metric projector is invented',src.includes('bridge.report({})'));
check('exports player stats in tracking report',src.includes('playerStats,unavailable:playerStats.unavailable'));
check('renders individual player cards',src.includes('renderPlayerStats(playerStats)'));
check('delegates cards to canonical renderer',src.includes('CAYPlayerCardRenderer')&&src.includes('report.playerCards')&&src.includes('renderer.render(model,cards)'));
check('fails closed instead of rendering parallel stats',src.includes('Aucune statistique parallèle n’est affichée')&&!src.includes('cards.innerHTML=players.map'));
check('labels persistent global player id on video overlay',src.includes("+' #'+a.trackId"));
check('does not draw path across segments',src.includes('filter(p=>p.segment===seg)'));
check('shows team per-instant coverage',src.includes('Équipe par instant'));
check('confirmed substitutions stay unavailable without validated event',src.includes('Remplacements confirmés : <b>INDISPONIBLE</b>'));
check('does not silently skip frames without a field polygon',!src.includes('poly=trackingPoly(t,c);if(!poly)continue'));
check('marks missing-field frame explicitly unavailable',src.includes("markUnavailableTrackingFrame(bridge,frames,t,c,i,times.length,'FIELD_POLYGON_UNAVAILABLE'"));
check('marks detector inference failure explicitly unavailable',src.includes("markUnavailableTrackingFrame(bridge,frames,t,c,i,times.length,'DETECTOR_INFERENCE_FAILED'"));
check('continues after detector frame failure',/try\{raw=await detectTracking\(model,c\);\}\s*catch\(_\)\{[\s\S]*DETECTOR_INFERENCE_FAILED[\s\S]*continue;\s*\}/.test(src));
check('fails closed if unavailable-frame guard is missing',src.includes("throw new Error('garde couverture frames indisponibles absent')"));
check('exports attempted usable unavailable observation coverage',src.includes('observationCoverage:{attempted:')&&src.includes('usable:playerStats.bridge?.usableObservationFrames')&&src.includes('unavailable:playerStats.bridge?.unavailableObservationFrames'));
check('shows attempted and unavailable frames in UI',src.includes('frame(s) tentée(s)')&&src.includes('indisponible(s)'));
check('success status exposes observation coverage',src.includes("• couverture '+Math.round((playerStats.bridge?.observationCoverage||0)*100)+' %"));
check('uses C.A. Yenne player-card terminology',src.includes('FICHES JOUEURS — ANALYSE C.A. YENNE'));
check('legacy duplicate player-card renderer stays removed',!src.includes('function stateBadge(')&&!src.includes('function heatmapHtml(')&&!src.includes('Première / dernière apparition'));
console.log(`runtime integration: ${pass} PASS / ${fail} FAIL`);
if(fail)process.exit(1);