const fs=require('fs');
const src=fs.readFileSync('stable_runtime_tracking_v2.js','utf8');
let pass=0,fail=0;
function check(name,cond){if(cond){console.log('PASS',name);pass++;}else{console.error('FAIL',name);fail++;}}
check('uses long-term bridge',src.includes('CAYStableTrackingBridge.create'));
check('hard cap 11 players',src.includes('maxPlayers:11'));
check('preserves segment breaks',src.includes('segmentBreak'));
check('appearance vector for re-identification',src.includes('appearanceVector(cls.feature)'));
check('no metric projector is invented',src.includes('bridge.report({})'));
check('shows metric unavailable when uncalibrated',src.includes('projection métrique non validée'));
check('exports player stats in tracking report',src.includes('playerStats,unavailable:playerStats.unavailable'));
check('renders individual player cards',src.includes('renderPlayerStats(playerStats)'));
check('labels persistent global player id',src.includes("+' #'+a.trackId"));
check('does not draw path across segments',src.includes('filter(p=>p.segment===seg)'));
check('shows roster visibility state',src.includes('stateBadge(rs.visibility)'));
check('late appearance is not promoted to confirmed substitution',src.includes('Apparu plus tard — remplacement NON confirmé'));
check('shows first and last appearance',src.includes('Première / dernière apparition'));
check('shows presence intervals',src.includes('Intervalles : '+"'+intervalsHtml(p.presenceIntervals)+'"));
check('shows identity confidence',src.includes('identité '+"'+conf+'"));
check('shows team per-instant coverage',src.includes('Équipe par instant'));
check('confirmed substitutions stay unavailable without validated event',src.includes('Remplacements confirmés : <b>INDISPONIBLE</b>'));
console.log(`runtime integration: ${pass} PASS / ${fail} FAIL`);
if(fail)process.exit(1);
