const assert=require('assert');
const {decideTrackingCandidatePromotion}=require('../tracking_candidate_promotion_gate_v1.js');
const evaluable={quality:'EVALUABLE',crossSegmentSafetyQuality:'EVALUABLE',crossSegmentUnsafeCarryoverRate:0};
const safe=decideTrackingCandidatePromotion({before:evaluable,after:evaluable,delta:{reidRecoveryRate:.1,longGapRecoveryRate:.2,crossSegmentUnsafeCarryoverRate:0,unsafeCrossSegmentSameId:0,failedReidentifications:-1}});
assert.strictEqual(safe.promotable,true);
assert.strictEqual(safe.status,'PROMOTABLE');
assert.ok(safe.gains.includes('reid_recovery'));
const unsafe=decideTrackingCandidatePromotion({before:evaluable,after:{...evaluable,crossSegmentUnsafeCarryoverRate:.1},delta:{reidRecoveryRate:.5,longGapRecoveryRate:.5,crossSegmentUnsafeCarryoverRate:.1,unsafeCrossSegmentSameId:1,failedReidentifications:-5}});
assert.strictEqual(unsafe.promotable,false);
assert.ok(unsafe.reasons.includes('unsafe_cross_segment_carryover'));
assert.ok(unsafe.reasons.includes('unsafe_carryover_regression'));
assert.ok(unsafe.reasons.includes('unsafe_same_id_count_regression'));
const unavailable=decideTrackingCandidatePromotion({before:evaluable,after:{quality:'INDISPONIBLE',crossSegmentSafetyQuality:'INDISPONIBLE',crossSegmentUnsafeCarryoverRate:null},delta:{reidRecoveryRate:null,longGapRecoveryRate:null}});
assert.strictEqual(unavailable.promotable,false);
assert.ok(unavailable.reasons.includes('candidate_identity_not_evaluable'));
assert.ok(unavailable.reasons.includes('candidate_cross_segment_safety_not_evaluable'));
assert.ok(unavailable.reasons.includes('no_predeclared_identity_gain'));
console.log('tracking_candidate_promotion_gate_nonregression: PASS');
