const assert=require('assert');
const stats=require('../player_stats_v1.js');
let pass=0; const ok=(name,fn)=>{fn();pass++;console.log('PASS',name)};
const raw={globalId:1,cat:'team',fullPath:[],segmentsSeen:[1,2]};
for(let i=0;i<6;i++)raw.fullPath.push({x:.10+i*.01,y:.20,time:i,segment:1});
for(let i=6;i<11;i++)raw.fullPath.push({x:.20+(i-6)*.01,y:.30,time:i,segment:2});
const summaryTrack={id:1,cat:'team',segments:[1,2],firstTime:0,lastTime:10,observedDuration:9,observations:11,reidentifications:1,mergedFrom:[],identityConfidence:.9,normalizedTravel:.1,quality:'FIABLE',dataQuality:{identity:'FIABLE'}};
const state={segments:2,archive:[],active:[raw]};
const core={summary:()=>({segments:2,rosterTotal:1,maxVisible:1,tracks:[summaryTrack]})};
ok('heatmap keeps observations',()=>assert.equal(stats.heatmap(raw.fullPath).observations,11));
const projectors={1:p=>({x:p.x*105,y:p.y*68})};
const m=stats.metricForTrack(raw,projectors);
ok('partial metric coverage',()=>assert(m.metricCoverage>0&&m.metricCoverage<1));
ok('metric distance available only on calibrated segment',()=>assert(m.distanceM>0));
ok('quality partial when only one segment calibrated',()=>assert.equal(m.quality,'PARTIEL'));
ok('no fake metric without projector',()=>{const x=stats.metricForTrack(raw,{});assert.equal(x.distanceM,null);assert.equal(x.quality,'INDISPONIBLE')});
const report=stats.buildReport(state,core,projectors);
ok('report has per-player card',()=>assert.equal(report.players.length,1));
ok('team metric counts only measured players',()=>assert.equal(report.team.playersWithMetricData,1));
ok('unsupported event stats remain unavailable',()=>assert(report.unavailable.possession&&report.unavailable.passes&&report.unavailable.shots));
const jumpTrack={fullPath:[{x:0,y:0,time:0,segment:1},{x:1,y:1,time:1,segment:1}]};
ok('implausible speed rejected',()=>assert.equal(stats.metricForTrack(jumpTrack,{1:p=>({x:p.x*105,y:p.y*68})}).distanceM,null));
ok('metric speed available when calibrated',()=>assert(m.maxSpeedKmh!==null&&m.avgSpeedKmh!==null));
console.log(`RESULT ${pass}/10`);
